apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: frenzy669/tzach-backend:latest  
        imagePullPolicy: Always  
        ports:
        - containerPort: 5010
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_NAME
          value: crypto_db
---
apiVersion: v1
kind: Service
meta
